name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workspace

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx eslint .
